### ISSUE TITLE
Appliance missing useful (necessary) tools

### ISSUE THREAD

**Issue by Megachip** [Uninett/navappliance#2]
Like:
- dhcping
- smbclient

**Comment by lunkwill42** [comment]
I'd say that this probably deserves an issue in the nav-debian repository: Since some NAV tools have these optional dependencies, they should be recommended by the NAV package itself. Then all the appliance install scripts need to do is to ensure recommended packages are also installed.

**Comment by lunkwill42** [comment]
This was actually solved in the NAV Debian package itself, which now recommends these tools: https://github.com/Uninett/nav-debian/issues/17
