### ISSUE TITLE
apt-get is broken, interface name is not good and apache show internal error

### ISSUE THREAD

**Issue by tototey** [Uninett/navappliance#4]
lots of issues with this appliance, first time experiencing them
can't get my hands on version 5.5x of the appliance

ps: nav still rocks :)

**Comment by lunkwill42** [comment]
Thanks for the feedback, @tototey .

This really seems like three bug reports baked into one, but it lacks most of the information that would make it a useful bug report.

* How is apt-get broken?
* What does "interface name is not good" mean?

I can, however, confirm, that the web server isn't working, and that's definitely something we need to fix :)

**Comment by tototey** [comment]
Adding open-vm-tools leads to generating issues.
Interface is labelled enp0s3 in interface file but is detected as ens32
